// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG-Otm_A4mwyroxQQwXd6jd8tqV7CNAU0',
    appId: '1:651082830500:web:971b57bc6fcdd3ffe0cc31',
    messagingSenderId: '651082830500',
    projectId: 'flutter-firebase-f5b5a',
    authDomain: 'flutter-firebase-f5b5a.firebaseapp.com',
    storageBucket: 'flutter-firebase-f5b5a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB3TypP0kyHUf63RfeanupOeXd8BklaiQ',
    appId: '1:651082830500:android:1d2247e11b917a22e0cc31',
    messagingSenderId: '651082830500',
    projectId: 'flutter-firebase-f5b5a',
    storageBucket: 'flutter-firebase-f5b5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxcpM8esdQBzWKQ5vrXMlKOqH0z4dw8kE',
    appId: '1:651082830500:ios:41f95a2fa16d4a22e0cc31',
    messagingSenderId: '651082830500',
    projectId: 'flutter-firebase-f5b5a',
    storageBucket: 'flutter-firebase-f5b5a.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxcpM8esdQBzWKQ5vrXMlKOqH0z4dw8kE',
    appId: '1:651082830500:ios:41f95a2fa16d4a22e0cc31',
    messagingSenderId: '651082830500',
    projectId: 'flutter-firebase-f5b5a',
    storageBucket: 'flutter-firebase-f5b5a.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG-Otm_A4mwyroxQQwXd6jd8tqV7CNAU0',
    appId: '1:651082830500:web:6ea1d8acf2fb38fae0cc31',
    messagingSenderId: '651082830500',
    projectId: 'flutter-firebase-f5b5a',
    authDomain: 'flutter-firebase-f5b5a.firebaseapp.com',
    storageBucket: 'flutter-firebase-f5b5a.appspot.com',
  );
}
